Plug 'tpope/vim-surround'
Plug 'tpope/vim-eunuch'
Plug 'terryma/vim-multiple-cursors'
Plug 'Raimondi/delimitMate'
Plug 'michaeljsmith/vim-indent-object'
Plug 'tpope/vim-repeat'
Plug 'ntpeters/vim-better-whitespace'

Plug 'rchicoli/vim-zoomwin'
Plug 'airblade/vim-gitgutter'
